letter:
  sender:
    error-strategy: fail
  processing:
    overflow-strategy: terminate



spring:
  devtools:
    livereload:
      enabled: false
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket