letter:
  receiver:
    service-name: agent-smith-service
  sender:
    error-strategy: fail
  processing:
    time: 500
    random-delay: 0
    queue-size: 100
    concurrency-level: 8
    overflow-strategy: block


server:
  port: 8080

spring:
  application:
    order: 1
    id: ""
    name: big-bro-service${spring.application.id}
  cloud:
    consul:
      discovery:
        instance-group: big-bro-service
        service-name: big-bro-service
