letter:
  receiver:
    base-url: http://localhost:8080/
  sender:
    error-strategy: fail
  processing:
    time: 0
    random-delay: 0
    queue-size: 100
    concurrency-level: 1
    overflow-strategy: block


server:
  port: 8070

spring:
  application:
    order: 0
    id: ""
    name: pechkin-service${spring.application.id}
